[build]
  command = "sh netlify-build.sh"
  publish = "."

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/dbt-button-fix.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/campfire-daily-reflections.js"
  [headers.values]
    Cache-Control = "no-cache"
