// Run with Playwright installed and the app served at http://127.0.0.1:8765.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/Chicago',geolocation:{latitude:43.07,longitude:-89.4},permissions:['geolocation'],serviceWorkers:'block'});
 const page=await context.newPage(); const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('grizzlyjohn:installComplete','true')});
 let mode='ok';let request;
 const fixture={current:{time:'2026-10-01T12:15',temperature_2m:68,apparent_temperature:67,weather_code:2,wind_speed_10m:8},daily:{time:['2026-10-01','2026-10-02','2026-10-03','2026-10-04','2026-10-05','2026-10-06'],temperature_2m_max:[72,73,74,75,76,77],temperature_2m_min:[50,51,52,53,54,55],precipitation_probability_max:[10,20,30,40,50,60],weather_code:[2,3,61,0,1,2]},hourly:{time:Array.from({length:24},(_,i)=>`2026-10-01T${String(i).padStart(2,'0')}:00`),temperature_2m:Array(24).fill(68),weather_code:Array(24).fill(2),precipitation_probability:Array(24).fill(15)}};
 await page.route('https://api.open-meteo.com/**',route=>{request=route.request().url();return mode==='fail'?route.fulfill({status:503,body:'Unavailable'}):route.fulfill({json:mode==='partial'?{current:fixture.current}:fixture});});
 await page.goto('http://127.0.0.1:8765');
 await page.locator('[data-nav="health"]').last().click();
 await page.locator('#healthSnapshotMeals input[data-meal-field="breakfast"]').check();
 await page.locator('#healthSnapshotMeals input[data-meal-field="lunch"]').check();
 await page.locator('#healthSnapshotMeals input[data-meal-field="dinner"]').check();
 await page.locator('#healthSnapshotMeals input[data-meal-field="snacks"]').check();
 await page.locator('#healthSnapshotMeals input[data-meal-field="lunch"]').uncheck();
 await page.locator('#healthSnapshotMeals input[data-meal-field="note"]').fill('Soup & toast <good>');
 const today=await page.evaluate(()=>window.GrizzlyJohnHealthV3.localDateKey(new Date()));
 const yesterday=await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);return window.GrizzlyJohnHealthV3.localDateKey(d)});
 await page.reload(); await page.locator('[data-nav="health"]').last().click();
 assert.equal(await page.locator('#healthSnapshotMeals [data-meal-field="breakfast"]').isChecked(),true);
 assert.equal(await page.locator('#healthSnapshotMeals [data-meal-field="lunch"]').isChecked(),false);
 assert.equal(await page.locator('#healthSnapshotMeals [data-meal-field="note"]').inputValue(),'Soup & toast <good>');
 if(today.slice(0,7)!==yesterday.slice(0,7)) await page.locator('#healthCalendarPrev').click();
 await page.locator(`[data-health-date="${yesterday}"]`).click();
 assert.equal(await page.locator('#healthSelectedDay [data-meal-field="breakfast"]').isChecked(),false);
 await page.locator('#healthSelectedDay [data-meal-field="dinner"]').check();
 await page.locator('#healthSelectedDay [data-meal-field="note"]').fill('Yesterday meal');
 await page.locator('#healthCalendarToday').click();
 assert.equal(await page.locator('#healthSelectedDay [data-meal-field="note"]').inputValue(),'Soup & toast <good>');
 if(today.slice(0,7)!==yesterday.slice(0,7)) await page.locator('#healthCalendarPrev').click();
 await page.locator(`[data-health-date="${yesterday}"]`).click();
 assert.equal(await page.locator('#healthSelectedDay [data-meal-field="note"]').inputValue(),'Yesterday meal');
 const link=page.getByRole('link',{name:/SSM\/Dean MyChart/});assert.equal(await link.getAttribute('href'),'https://mychart.ssmhc.com/mychart/Authentication/Login');assert.equal(await link.getAttribute('target'),'_blank');
 await page.route('https://mychart.ssmhc.com/**',r=>r.fulfill({body:'Portal test'}));
 const popupPromise=context.waitForEvent('page');await link.click();const popup=await popupPromise;await popup.waitForLoadState();assert.match(popup.url(),/^https:\/\/mychart.ssmhc.com\/mychart\/Authentication\/Login/);await popup.close();
 await page.locator('#healthDoctorView').click();assert.equal(await page.locator('#healthDoctorSummary').isVisible(),true);
 await page.locator('#healthSnapshotMeals').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/grizzly-health-mobile.png'});
 await page.locator('[data-nav="today"]').last().click();await page.locator('#loadWeather').click();await page.locator('.weather-day').first().waitFor();
 assert.equal(await page.locator('.weather-day').count(),5);assert.equal(await page.locator('.weather-hour').count(),11);assert.match(await page.locator('.weather-hour').first().innerText(),/1 PM/);assert.match(request,/forecast_days=6/);
 assert.equal(await page.locator('#weatherTemp').innerText(),'68°');
 await page.locator('#weatherCard').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/grizzly-weather-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 for(const width of [320,1200]) {await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await page.setViewportSize({width:390,height:844});
 mode='fail';await page.locator('#loadWeather').click();await page.waitForFunction(()=>document.querySelector('#weatherStatus').textContent.includes('Could not update'));
 mode='partial';await page.locator('#loadWeather').click();await page.waitForFunction(()=>document.querySelector('#weatherDaily').textContent.includes('unavailable'));
 await context.clearPermissions();await page.locator('#loadWeather').click();await page.waitForFunction(()=>document.querySelector('#weatherStatus').textContent.includes('Location is off'));
 await page.locator('[data-nav="health"]').last().click();assert.equal(await page.locator('#healthSnapshotMeals [data-meal-field="breakfast"]').isChecked(),true);
 assert.ok(errors.every(message=>message==='missing ) after argument list'),JSON.stringify(errors));console.log('Known baseline DBT syntax error occurrences:',errors.length);console.log('PASS: mobile layout, meals reload/date switching, external portal, Doctor View, current/hourly/five-day weather, API failure, missing forecast, location denial; no new JS errors (baseline DBT error excluded)');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
